### PR TITLE
Securty

### PR DESCRIPTION
**Pull request by kevinperdana1992**

### CODE REVIEW

**Review by Assawal — APPROVED** [review]
Update it as changes

**Review by kingthrd — CHANGES_REQUESTED** [review]
I’m trying to verify my tokens and have the contract under my name? How can I do that?

**Comment by kevinperdana1992** [comment]
Permintaan tarik selesai

**Review by MaryJaneLove4 — COMMENTED** [review]
V pohodě

**Review by MaryJaneLove4 — COMMENTED** [review]
good

**Review by MaryJaneLove4 — COMMENTED** [review]
1

**Comment by kevinperdana1992** [comment]
coinbase.com/join/suhard_u6?src=android-link

Pada tanggal Jum, 6 Agt 2021 6:22 AM, MaryJaneLove4 <
***@***.***> menulis:

**Pull request closed without merging**
