### PR TITLE
Baw42895 patch 2

### PR DESCRIPTION
**Pull request by baw42895**

### CODE REVIEW

**Review by vtc999 — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Comment by baw42895** [comment]
Can someone help me

**Review by que1414 — APPROVED** [review]

**Review by prowebdesignku — APPROVED** [review]

**Review by prowebdesignku — APPROVED** [review]

**Review by MaryJaneLove4 — APPROVED** [review]
OK

**Review by MaryJaneLove4 — APPROVED** [review]
It is right...yeah?

**Review by Hbutlercapone — APPROVED** [review]
All green blocks. Word

**Review by Hbutlercapone — COMMENTED** [review]
Spam?

**Comment by ToTheHighestTopMoon** [comment]
What’s contract address..?

**Review by MaryJaneLove4 — APPROVED** [review]

**Review by MaryJaneLove4 — APPROVED** [review]

**Review by MaryJaneLove4 — APPROVED** [review]

**Review by MaryJaneLove4 — APPROVED** [review]

**Review by stahlbrand94 — APPROVED** [review]

**Review by MaryJaneLove4 — APPROVED** [review]

**Review by MaryJaneLove4 — APPROVED** [review]

**Review by MaryJaneLove4 — APPROVED** [review]
ok

**Review by MaryJaneLove4 — COMMENTED** [review]
???

**Pull request closed without merging**
