### PR TITLE
Show Proxy Implementation ABI

### PR DESCRIPTION
**Pull request by wjmelements**
#### Changes
This implements https://github.com/etherscan/writecontract/issues/15

I refactor the row-adding logic into a function that takes a contract address. I limit the recursion depth to thwart antagonistic proxy chains.

Reviewers @khairulmax

### CODE REVIEW

**Comment by wjmelements** [comment]
I have trouble testing this because of https://github.com/etherscan/writecontract/issues/11

**Comment by wjmelements** [comment]
Let me know if you want the UI to look any different.

**Comment by wjmelements** [comment]
Test Addresses (TrustToken):
* 0x0000000000085d4780B73119b644AE5ecd22b376
* 0x0000000000013949F288172bD7E36837bDdC7211
* 0x0000000000075EfBeE23fe2de1bd0b7690883cc9
Test Addresses (Other):
* 0x8E870D67F660D95d5be530380D0eC0bd388289E1
* 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

**Comment by wjmelements** [comment]
I have found a workaround for testing, though it's not ideal because it doesn't do the ABI network requests.

**Comment by hanislong** [comment]
here is still something down to?

**Comment by wjmelements** [comment]
Screenshot, using mock data
```
data = {
            status: 1,
            result: contractAddress === "0x0000000000085d4780B73119b644AE5ecd22b376"
                ? JSON.stringify([{
                    name: "implementation",
                    inputs: [],
                    constant: true,
                }, {
                    name: "upgradeTo",
                    inputs: [
                        {
                            name: "implementation",
                            type: "address",
                        }
                    ],
                    constant: false,
                }])
                : JSON.stringify([{
                    name: "claim",
                    inputs: [],
                    constant: false,
                }]),
        };
```

screen shot 2019-01-24 at 2 35 51 pm

**Comment by wjmelements** [comment]
You can block spam with this easy trick:
screen shot 2019-01-24 at 2 52 20 pm

**Comment by hanislong** [comment]
on pull request

**Comment by WET9** [comment]
All issue please sent gmail / code anny Issue to : cryptocurenncy@gmail.com

**Review by jocelynaddy — APPROVED** [review]

**Review by jocelynaddy — APPROVED** [review]

**Comment by jocelynaddy** [comment]
Needsigniturehadh

**Review by jocelynaddy — APPROVED** [review]

**Review by jocelynaddy — APPROVED** [review]

**Review by soulfulAdam — APPROVED** [review]

**Review by soulfulAdam — COMMENTED** [review]
.

**Comment by Wrathcoin** [comment]
Hmmm

**Review by Wrathcoin — APPROVED** [review]
Hmmm

**Pull request merged**
