### PR TITLE
0x ee4 cf8 c1c4 dd49b f8 b917178810b4 fc1ba47093 b

### PR DESCRIPTION
**Pull request by 11477398000106**

### CODE REVIEW

**Comment by Ziqhoulets** [comment]
0xEe4CF8C1c4DD49bF8B917178810b4Fc1ba47093B

**Comment by Ziqhoulets** [comment]
0x52A2C5e02EB3779BD23E8d1C43a19C7412de883E

**Review by sahlawiz — APPROVED** [review]

**Review by wanchalong19 — APPROVED** [review]

**Comment by 11477398000106** [comment]
> 0xEe4CF8C1c4DD49bF8B917178810b4Fc1ba47093B

**Review by BangkitSedar2 — CHANGES_REQUESTED** [review]
>

**Pull request closed without merging**
