### PR TITLE
Fresh.gist.data.ethscan

### PR DESCRIPTION
**Pull request by PaulinaParangerHr**
Web3 connection with Etherscan.io

### CODE REVIEW

**Review by atyhieu — COMMENTED** [review]
Thankss

**Review by koosy79 — APPROVED** [review]

**Comment by mdazam7373** [comment]
0xac51066d7bec65dc4589368da368b212745d63e8

**Comment by mdazam7373** [comment]
0xac51066d7bec65dc4589368da368b212745d63e8

**Review by atyhieu — APPROVED** [review]

**Comment by nguyenducsang** [comment]
Siêu

**Review by atyhieu — APPROVED** [review]

**Pull request closed without merging**
